function [] = exercise419bernsteinPlotter()

    evaluateSetDimension = 10^(4);

    [bernsteinEvaluationInterval, bernsteinEvaluatedFunctionValuesVector,...
    bernsteinInterpolationAscisseVector, bernsteinFunctionValuesVector,...
    bernsteinNormalInterpolatedValues, bernsteinNotAKnotInterpolatedValues] =...
        exercise419bernstein(evaluateSetDimension, 10);

    plot(bernsteinEvaluationInterval, bernsteinEvaluatedFunctionValuesVector, "b", ...
        bernsteinEvaluationInterval, bernsteinNormalInterpolatedValues, "r", ...
        bernsteinEvaluationInterval, bernsteinNotAKnotInterpolatedValues, "g", ...
        bernsteinInterpolationAscisseVector, bernsteinFunctionValuesVector, "+");
    grid;
    print 'exercise419-bernsteinInterpolationPlotOutput.tex' '-dTex' '-S800, 600';
endfunction
